version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src # Ajuda a prevenir a não gravação do node_modules
    command: npm run production
