version: "3"

services:
  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src # Ajuda a prevenir a não gravação do node_modules