version: "3"

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/app/src # Ajuda a prevenir a não gravação do node_modules